let PRED, RES, PARTICIPANTES=[], MATCHES=[], PLAYED=[], PENDING=[], RANKING=[];
const TABS=[['inicio','🏠 Inicio'],['ranking','🏆 Ranking'],['partidos','⚽ Partidos'],['llave','🏆 Llave'],['mundial','🌎 Mundial'],['salon','🥇 Salón']];
const FLAGS={'México':'🇲🇽','Sudáfrica':'🇿🇦','Corea del Sur':'🇰🇷','Chequia':'🇨🇿','Canadá':'🇨🇦','Bosnia':'🇧🇦','Qatar':'🇶🇦','Suiza':'🇨🇭','Haití':'🇭🇹','Escocia':'🏴󠁧󠁢󠁳󠁣󠁴󠁿','Brasil':'🇧🇷','Marruecos':'🇲🇦','EE.UU.':'🇺🇸','Paraguay':'🇵🇾','Australia':'🇦🇺','Turquía':'🇹🇷','C. de Marfil':'🇨🇮','Ecuador':'🇪🇨','Alemania':'🇩🇪','Curazao':'🇨🇼','P. Bajos':'🇳🇱','Japón':'🇯🇵','Suecia':'🇸🇪','Túnez':'🇹🇳','Egipto':'🇪🇬','Irán':'🇮🇷','Bélgica':'🇧🇪','N. Zelanda':'🇳🇿','España':'🇪🇸','Uruguay':'🇺🇾','Cabo Verde':'🇨🇻','Arabia Saudita':'🇸🇦','Francia':'🇫🇷','Noruega':'🇳🇴','Senegal':'🇸🇳','Irak':'🇮🇶','Argentina':'🇦🇷','Austria':'🇦🇹','Argelia':'🇩🇿','Jordania':'🇯🇴','Colombia':'🇨🇴','Portugal':'🇵🇹','Congo':'🇨🇩','Uzbekistán':'🇺🇿','Inglaterra':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Ghana':'🇬🇭','Croacia':'🇭🇷','Panamá':'🇵🇦'};
const MATCH_SCHEDULE={p001:'2026-06-11T19:00:00Z',p002:'2026-06-12T02:00:00Z',p003:'2026-06-12T19:00:00Z',p004:'2026-06-13T01:00:00Z',p008:'2026-06-13T19:00:00Z',p007:'2026-06-13T22:00:00Z',p005:'2026-06-14T01:00:00Z',p006:'2026-06-14T04:00:00Z',p010:'2026-06-14T17:00:00Z',p011:'2026-06-14T20:00:00Z',p009:'2026-06-14T23:00:00Z',p012:'2026-06-15T02:00:00Z',p014:'2026-06-15T16:00:00Z',p016:'2026-06-15T19:00:00Z',p013:'2026-06-15T22:00:00Z',p015:'2026-06-16T01:00:00Z',p017:'2026-06-16T19:00:00Z',p018:'2026-06-16T22:00:00Z',p019:'2026-06-17T01:00:00Z',p020:'2026-06-17T04:00:00Z',p023:'2026-06-17T17:00:00Z',p022:'2026-06-17T20:00:00Z',p021:'2026-06-17T23:00:00Z',p024:'2026-06-18T02:00:00Z',p025:'2026-06-18T16:00:00Z',p026:'2026-06-18T19:00:00Z',p027:'2026-06-18T22:00:00Z',p028:'2026-06-19T01:00:00Z',p032:'2026-06-19T19:00:00Z',p030:'2026-06-19T22:00:00Z',p029:'2026-06-20T00:30:00Z',p031:'2026-06-20T03:00:00Z',p035:'2026-06-20T17:00:00Z',p033:'2026-06-20T20:00:00Z',p034:'2026-06-21T00:00:00Z',p036:'2026-06-21T04:00:00Z',p038:'2026-06-21T16:00:00Z',p039:'2026-06-21T19:00:00Z',p037:'2026-06-21T22:00:00Z',p040:'2026-06-22T01:00:00Z',p043:'2026-06-22T17:00:00Z',p042:'2026-06-22T21:00:00Z',p041:'2026-06-23T00:00:00Z',p044:'2026-06-23T03:00:00Z',p047:'2026-06-23T17:00:00Z',p045:'2026-06-23T20:00:00Z',p046:'2026-06-23T23:00:00Z',p048:'2026-06-24T02:00:00Z',p051:'2026-06-24T19:00:00Z',p052:'2026-06-24T19:00:00Z',p049:'2026-06-24T22:00:00Z',p050:'2026-06-24T22:00:00Z',p053:'2026-06-25T01:00:00Z',p054:'2026-06-25T01:00:00Z',p056:'2026-06-25T20:00:00Z',p055:'2026-06-25T20:00:00Z',p058:'2026-06-25T23:00:00Z',p057:'2026-06-25T23:00:00Z',p059:'2026-06-26T02:00:00Z',p060:'2026-06-26T02:00:00Z',p061:'2026-06-26T19:00:00Z',p062:'2026-06-26T19:00:00Z',p066:'2026-06-27T00:00:00Z',p065:'2026-06-27T00:00:00Z',p064:'2026-06-27T03:00:00Z',p063:'2026-06-27T03:00:00Z',p067:'2026-06-27T21:00:00Z',p068:'2026-06-27T21:00:00Z',p071:'2026-06-27T23:30:00Z',p072:'2026-06-27T23:30:00Z',p070:'2026-06-28T02:00:00Z',p069:'2026-06-28T02:00:00Z',p073:'2026-06-28T19:00:00Z',p074:'2026-06-29T17:00:00Z',p075:'2026-06-29T20:30:00Z',p076:'2026-06-30T01:00:00Z',p077:'2026-06-30T17:00:00Z',p078:'2026-06-30T21:00:00Z',p079:'2026-07-01T01:00:00Z',p080:'2026-07-01T16:00:00Z',p081:'2026-07-01T20:00:00Z',p082:'2026-07-02T00:00:00Z',p083:'2026-07-02T19:00:00Z',p084:'2026-07-02T23:00:00Z',p085:'2026-07-03T03:00:00Z',p086:'2026-07-03T18:00:00Z',p087:'2026-07-03T22:00:00Z',p088:'2026-07-04T01:30:00Z'};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function norm(s){return (s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function teamKey(s){return norm(s).replace(/[^a-z0-9]/g,'')}
function flag(t){return FLAGS[t]||'🏳️'}
function outcome(a,b){return +a>+b?'L':+a<+b?'V':'E'}
function points(ph,pa,rh,ra){ph=+ph;pa=+pa;rh=+rh;ra=+ra;if(ph===rh&&pa===ra)return 5+rh+ra;const ok=outcome(ph,pa)===outcome(rh,ra);const bonus=(ph===rh&&rh>0)?rh:((pa===ra&&ra>0)?ra:0);return ok?3+bonus:bonus}
function isFinal(m){return m.estado==='finalizado'&&m.golesLocal!=null&&m.golesVisitante!=null}
function isLive(m){return m.estado==='en_vivo'&&m.golesLocal!=null&&m.golesVisitante!=null}
function isScoreable(m){return isFinal(m)||isLive(m)}
function mt(m){return MATCH_SCHEDULE[m.id]?new Date(MATCH_SCHEDULE[m.id]).getTime():(m.matchId||999)*999999999}
function fmt(m){return MATCH_SCHEDULE[m.id]?new Date(MATCH_SCHEDULE[m.id]).toLocaleString('es-CO',{weekday:'short',hour:'numeric',minute:'2-digit',hour12:true}):''}
function pct(n,d){return Math.round((n/(d||1))*100)}
function medal(i){return i===1?'🥇':i===2?'🥈':i===3?'🥉':'#'+i}
function roundOfMatch(m){const n=m.matchId||0;if(n>=73&&n<=88)return '16avos';if(n>=89&&n<=96)return 'Octavos';if(n>=97&&n<=100)return 'Cuartos';if(n>=101&&n<=102)return 'Semis';if(n>=103)return 'Final';return 'Grupos'}
function isKO(m){return (m.matchId||0)>=73}
function exactPotentialPoints(score){const [a,b]=String(score).split('-').map(Number);return 5+(Number.isFinite(a)?a:0)+(Number.isFinite(b)?b:0)}
function groupLetters(){return [...new Set(MATCHES.map(m=>m.grupo).filter(Boolean))].sort()}
function groupMatches(g){return MATCHES.filter(m=>m.grupo===g)}
function addRow(rows,l,v,gl,gv){for(const t of [l,v])if(!rows[t])rows[t]={team:t,pj:0,pts:0,gf:0,gc:0,gd:0,w:0,d:0,l:0};const A=rows[l],B=rows[v];A.pj++;B.pj++;A.gf+=+gl;A.gc+=+gv;B.gf+=+gv;B.gc+=+gl;A.gd=A.gf-A.gc;B.gd=B.gf-B.gc;if(+gl>+gv){A.w++;B.l++;A.pts+=3}else if(+gl<+gv){B.w++;A.l++;B.pts+=3}else{A.d++;B.d++;A.pts++;B.pts++}}
function standings(g){const rows={};groupMatches(g).forEach(m=>{if(!rows[m.local])rows[m.local]={team:m.local,pj:0,pts:0,gf:0,gc:0,gd:0,w:0,d:0,l:0};if(!rows[m.visitante])rows[m.visitante]={team:m.visitante,pj:0,pts:0,gf:0,gc:0,gd:0,w:0,d:0,l:0};if(isFinal(m))addRow(rows,m.local,m.visitante,m.golesLocal,m.golesVisitante)});return Object.values(rows).sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.gc-b.gc||a.team.localeCompare(b.team))}
function actualGroupStanding(g){const ms=groupMatches(g);return ms.length>=6&&ms.every(isFinal)?standings(g):null}
function predGroupStanding(g,p){if(p.grupos&&Array.isArray(p.grupos[g]))return p.grupos[g].map(team=>({team}));const rows={};for(const m of groupMatches(g)){const pr=p.predicciones?.[m.id];if(!pr)return null;addRow(rows,m.local,m.visitante,pr.golesLocal,pr.golesVisitante)}return Object.values(rows).sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf)}
function groupBonus(p){let total=0,hits=0;groupLetters().forEach(g=>{const real=actualGroupStanding(g), pred=predGroupStanding(g,p);if(!real||!pred)return;[4,3,1,1].forEach((val,i)=>{if(teamKey(real[i]?.team)===teamKey(pred[i]?.team)){total+=val;hits++}})});return{total,hits}}
function calculate(){PLAYED=MATCHES.filter(isScoreable).sort((a,b)=>mt(a)-mt(b));PENDING=MATCHES.filter(m=>!isScoreable(m)).sort((a,b)=>mt(a)-mt(b));RANKING=PARTICIPANTES.map(p=>{let pts=0,exact=0,hit=0,last=[],koPts=0,koExact=0,koHit=0;const koByRound={};PLAYED.forEach(m=>{const pr=p.predicciones?.[m.id];if(!pr)return;const s=points(pr.golesLocal,pr.golesVisitante,m.golesLocal,m.golesVisitante);pts+=s;const ex=+pr.golesLocal===+m.golesLocal&&+pr.golesVisitante===+m.golesVisitante;const ok=outcome(pr.golesLocal,pr.golesVisitante)===outcome(m.golesLocal,m.golesVisitante);if(ex)exact++;if(ok)hit++;const item={m,pr,s,ex,ok};last.unshift(item);if(isKO(m)){koPts+=s;if(ex)koExact++;if(ok)koHit++;const r=roundOfMatch(m);if(!koByRound[r])koByRound[r]={pts:0,hit:0,exact:0,total:0,items:[]};koByRound[r].pts+=s;koByRound[r].total++;if(ok)koByRound[r].hit++;if(ex)koByRound[r].exact++;koByRound[r].items.unshift(item)}});const gb=groupBonus(p);pts+=gb.total;return{...p,pts,exact,hit,pct:PLAYED.length?pct(hit,PLAYED.length):0,last,groupPts:gb.total,groupHits:gb.hits,koPts,koExact,koHit,koByRound}}).sort((a,b)=>b.pts-a.pts||b.exact-a.exact||b.hit-a.hit||a.nombre.localeCompare(b.nombre));RANKING.forEach((p,i)=>p.pos=i+1)}
function countHonor(key){const map={};PARTICIPANTES.forEach(p=>{const v=p.honor?.[key];if(v)map[v]=(map[v]||0)+1});return Object.entries(map).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))}
function countPredictedWinner(match){const map={};PARTICIPANTES.forEach(p=>{const pr=p.predicciones?.[match.id];if(!pr)return;const o=outcome(pr.golesLocal,pr.golesVisitante);const val=o==='L'?match.local:o==='V'?match.visitante:'Empate';map[val]=(map[val]||0)+1});return Object.entries(map).sort((a,b)=>b[1]-a[1])}
function topMetric(key,label){return RANKING.slice().sort((a,b)=>b[key]-a[key]||b.pts-a.pts).slice(0,5).map((p,i)=>`<div class="barrow"><div class="barhead"><span>${medal(i+1)} ${esc(p.nombre)}</span><b>${p[key]} ${label}</b></div><div class="bar"><div class="fill" style="width:${pct(p[key],RANKING[0]?.[key]||1)}%"></div></div></div>`).join('')}
function initNav(){document.getElementById('nav').innerHTML=TABS.map(([id,txt])=>`<button onclick="showTab('${id}')" id="nav-${id}">${txt}</button>`).join('');document.getElementById('bottom').innerHTML=TABS.map(([id,txt])=>`<button onclick="showTab('${id}')" id="bot-${id}"><b>${txt.split(' ')[0]}</b>${txt.split(' ').slice(1).join(' ')}</button>`).join('')}
function showTab(id){document.querySelectorAll('.section').forEach(s=>s.classList.toggle('act',s.id===id));document.querySelectorAll('.nav button,.bottom button').forEach(b=>b.classList.remove('act'));document.getElementById('nav-'+id)?.classList.add('act');document.getElementById('bot-'+id)?.classList.add('act');window.scrollTo({top:0,behavior:'smooth'})}
function liveOrNext(){const live=MATCHES.filter(isLive).sort((a,b)=>mt(a)-mt(b));if(live.length)return live[0];return PENDING[0]}
function renderDashboard(){const leader=RANKING[0], focus=liveOrNext(), topExact=RANKING.slice().sort((a,b)=>b.exact-a.exact)[0];const progress=pct(PLAYED.length,MATCHES.length);document.getElementById('inicio').innerHTML=`<div class="grid4"><div class="card dash"><div class="cb"><span>👑 líder actual</span><b>${esc(leader?.nombre||'-')}</b><small>${leader?.pts||0} puntos · ${leader?.exact||0} exactos</small></div></div><div class="card dash"><div class="cb"><span>⚽ partido</span><b>${focus?flag(focus.local)+' '+esc(focus.local):'-'}</b><small>${focus?`${esc(focus.visitante)} ${flag(focus.visitante)} · ${isLive(focus)?'EN VIVO':fmt(focus)}`:'Sin próximos'}</small></div></div><div class="card dash"><div class="cb"><span>🎯 francotirador</span><b>${esc(topExact?.nombre||'-')}</b><small>${topExact?.exact||0} marcadores exactos</small></div></div><div class="card dash"><div class="cb"><span>🌎 avance</span><b>${PLAYED.length}/${MATCHES.length}</b><div class="bar"><div class="fill" style="width:${progress}%"></div></div><small>${progress}% del torneo jugado</small></div></div></div><br><div class="card"><div class="cb hero-card"><div>${playerCard(leader)}</div><div class="leader-detail"><h2>${esc(leader?.nombre||'')}</h2><div class="leader-points">${leader?.pts||0}</div><p class="subtle">Va de primero con ${leader?.hit||0} aciertos, ${leader?.exact||0} marcadores exactos y ${leader?.groupPts||0} puntos por posiciones de grupo.</p><div class="mini-stats"><div class="mini"><span>Acierto</span><b>${leader?.pct||0}%</b></div><div class="mini"><span>Exactos</span><b>${leader?.exact||0}</b></div><div class="mini"><span>Campeón</span><b>${flag(leader?.honor?.campeon)} ${esc(leader?.honor?.campeon||'-')}</b></div></div><br><button class="btn" onclick="openProfile('${leader?.id}')">Ver carta completa</button></div></div></div><br><div class="grid2"><div class="card"><div class="ch"><h3>📰 Feed de actividad</h3></div><div class="cb">${activityFeed()}</div></div><div class="card"><div class="ch"><h3>📈 Gráfica del ranking</h3></div><div class="cb">${rankingChart()}</div></div></div>`}
function playerCard(p){if(!p)return'';return `<div class="fifa-card"><div class="ovr">${Math.min(99,Math.round(60+p.pct/2+p.exact/3))}</div><div class="avatar">${p.pos===1?'👑':p.pos===2?'🥈':p.pos===3?'🥉':'⚽'}</div><div class="name">${esc(p.nombre)}</div><div class="meta">#${p.pos} · ${p.pts} pts</div><div class="meta">🎯 ${p.exact} exactos · ⚽ ${p.hit} aciertos</div></div>`}
function activityFeed(){const latest=PLAYED.slice(-6).reverse();let items=latest.map(m=>`<div class="feed-row"><div class="feed-ico">⚽</div><div><div class="feed-title">${flag(m.local)} ${esc(m.local)} ${m.golesLocal}-${m.golesVisitante} ${esc(m.visitante)} ${flag(m.visitante)}</div><div class="feed-sub">Ranking actualizado · mejoraron quienes acertaron este resultado.</div></div></div>`).join('');items+=`<div class="feed-row"><div class="feed-ico">👑</div><div><div class="feed-title">${esc(RANKING[0]?.nombre)} lidera la polla</div><div class="feed-sub">${RANKING[0]?.pts} puntos · ${RANKING[0]?.exact} marcadores exactos.</div></div></div>`;return items||'<div class="empty">Sin actividad todavía</div>'}
function rankingChart(){const max=RANKING[0]?.pts||1;return `<div class="ranking-chart">${RANKING.slice(0,10).map(p=>`<div class="chart-bar"><div class="chart-fill" style="height:${Math.max(28,pct(p.pts,max)*2)}px">${p.pos}</div><div class="chart-name">${esc(p.nombre.split(' ')[0])}<br><b>${p.pts}</b></div></div>`).join('')}</div><p class="subtle">Vista del top 10 actual. Esta gráfica se actualiza con cada cambio de resultados.</p>`}
function renderRanking(){document.getElementById('ranking').innerHTML=`<div class="card"><div class="ch"><h2>🏆 Ranking general</h2></div><div class="cb"><input class="search" id="q" placeholder="Buscar participante..." oninput="filterRanking()"><div id="rankList">${rankingRows(RANKING)}</div></div></div>`}
function rankingRows(arr){return arr.map(p=>`<div class="rank-row" onclick="openProfile('${p.id}')"><div class="pos">${medal(p.pos)}</div><div><div class="nm">${esc(p.nombre)}</div><div class="chips"><span class="chip">${p.hit} aciertos</span><span class="chip">${p.exact} exactos</span><span class="chip">${p.groupPts} pts grupos</span></div></div><div class="pts">${p.pts}<br><span class="subtle">pts</span></div></div>`).join('')}
function filterRanking(){const q=norm(document.getElementById('q').value);document.getElementById('rankList').innerHTML=rankingRows(RANKING.filter(p=>norm(p.nombre).includes(q)))}
function groupBetSummary(m){
  const winCounts={L:0,E:0,V:0};
  const scoreCounts={};
  PARTICIPANTES.forEach(p=>{
    const pr=p.predicciones?.[m.id];
    if(!pr||pr.golesLocal===undefined||pr.golesVisitante===undefined)return;
    const gl=+pr.golesLocal,gv=+pr.golesVisitante;
    if(Number.isNaN(gl)||Number.isNaN(gv))return;
    winCounts[outcome(gl,gv)]++;
    const k=`${gl}-${gv}`;
    scoreCounts[k]=(scoreCounts[k]||0)+1;
  });
  const scores=Object.entries(scoreCounts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));
  const total=scores.reduce((a,[,v])=>a+v,0)||1;
  const top=scores[0];
  const rows=scores.slice(0,12).map(([k,v],i)=>`<tr><td>${i===0?'👑 ':''}<b>${esc(k)}</b><div class="bet-meter"><span style="width:${pct(v,total)}%"></span></div></td><td class="bet-num">${v}</td><td class="bet-num">⭐ ${exactPotentialPoints(k)}</td></tr>`).join('');
  const other=Math.max(0,total-scores.slice(0,12).reduce((a,[,v])=>a+v,0));
  return `<div class="bet-card"><div class="bet-title">${flag(m.local)} ${esc(m.local).toUpperCase()} vs ${flag(m.visitante)} ${esc(m.visitante).toUpperCase()} <span class="pill-small">${fmt(m)||'pendiente'}</span></div><div class="grid3"><div class="mini"><span>Gana ${esc(m.local)}</span><b>${winCounts.L}</b></div><div class="mini"><span>Empate</span><b>${winCounts.E}</b></div><div class="mini"><span>Gana ${esc(m.visitante)}</span><b>${winCounts.V}</b></div></div><div class="bet-table-wrap"><table class="bet-table"><thead><tr><th>Marcador</th><th>Cantidad</th><th>Puntos si exacto</th></tr></thead><tbody>${rows}${other?`<tr><td>Otros marcadores</td><td class="bet-num">${other}</td><td class="bet-num">—</td></tr>`:''}<tr class="bet-total"><td>Total</td><td class="bet-num">${total}</td><td></td></tr></tbody></table></div><p class="subtle" style="margin-top:8px">Predicción colectiva: <b>${top?top[0]:'-'}</b> (${top?pct(top[1],total):0}% del grupo).</p></div>`
}
function groupBetsForUpcoming(){const ms=PENDING.filter(m=>m.id&&m.local&&m.visitante).slice(0,8);return ms.length?ms.map(groupBetSummary).join(''):'<div class="empty">No hay partidos pendientes con predicciones para comparar.</div>'}
function renderPartidos(){const cards=MATCHES.slice().sort((a,b)=>mt(a)-mt(b)).map(m=>`<div class="match-row"><div class="team">${flag(m.local)} ${esc(m.local)}</div><div class="score">${isScoreable(m)?`${m.golesLocal}-${m.golesVisitante}`:'vs'}</div><div class="team r">${esc(m.visitante)} ${flag(m.visitante)}</div><div class="status ${isLive(m)?'live':''}">${isLive(m)?'🟢 EN VIVO':isFinal(m)?'Finalizado':fmt(m)||'Pendiente'}</div></div>`).join('');document.getElementById('partidos').innerHTML=`<div class="grid2"><div class="card"><div class="ch"><h2>🔥 Lo que apostó el grupo</h2></div><div class="cb"><p class="subtle">Para los próximos partidos: tendencia del grupo y marcadores más repetidos.</p>${groupBetsForUpcoming()}</div></div><div class="card"><div class="ch"><h2>⚽ Todos los partidos</h2></div><div class="cb">${cards}</div></div></div>`}
function koLeaderboard(){const arr=RANKING.slice().sort((a,b)=>b.koPts-a.koPts||b.koExact-a.koExact||b.koHit-a.koHit).slice(0,10);return arr.map((p,i)=>`<div class="rank-row" onclick="openProfile('${p.id}')"><div class="pos">${medal(i+1)}</div><div><div class="nm">${esc(p.nombre)}</div><div class="subtle">${p.koHit} llaves acertadas · ${p.koExact} exactas</div></div><div class="pts">${p.koPts}<br><span class="subtle">pts</span></div></div>`).join('')||'<div class="empty">Aún no hay puntos de llaves.</div>'}
function koRoundSummary(){const rounds=['16avos','Octavos','Cuartos','Semis','Final'];return `<div class="ko-grid">${rounds.map(r=>{const ms=PLAYED.filter(m=>isKO(m)&&roundOfMatch(m)===r);const max=ms.length;const avg=max?Math.round(RANKING.reduce((a,p)=>a+(p.koByRound[r]?.hit||0),0)/RANKING.length):0;return `<div class="ko-mini"><span>${r}</span><b>${max?avg+'/'+max:'Pendiente'}</b><small class="subtle">promedio aciertos</small></div>`}).join('')}</div>`}
function renderLlave(){const kos=MATCHES.filter(m=>(m.matchId||0)>=73).sort((a,b)=>(a.matchId||0)-(b.matchId||0));document.getElementById('llave').innerHTML=`<div class="grid2"><div class="card"><div class="ch"><h2>🏆 Eliminatorias</h2></div><div class="cb"><p class="subtle">Cruces definidos y resultados de llaves.</p>${kos.map(m=>`<div class="match-row"><div class="team">${flag(m.local)} ${esc(m.local||'Por definir')}</div><div class="score">${isScoreable(m)?`${m.golesLocal}-${m.golesVisitante}`:'vs'}</div><div class="team r">${esc(m.visitante||'Por definir')} ${flag(m.visitante)}</div><div class="status">${isFinal(m)?'Finalizado':fmt(m)||'Pendiente'}</div></div>`).join('')}</div></div><div><div class="card"><div class="ch"><h2>🧮 Puntos de llaves</h2></div><div class="cb"><p class="subtle">Ranking solo con puntos obtenidos en eliminatorias.</p>${koLeaderboard()}</div></div><br><div class="card"><div class="ch"><h2>📌 Resumen por ronda</h2></div><div class="cb">${koRoundSummary()}</div></div></div></div>`}
function renderMundial(){const campeones=countHonor('campeon'), botin=countHonor('botin_oro'), balon=countHonor('balon_oro');const focus=liveOrNext();document.getElementById('mundial').innerHTML=`<div class="grid2"><div class="card"><div class="ch"><h2>🌍 Campeón más votado</h2></div><div class="cb">${bars(campeones,116)}</div></div><div class="card"><div class="ch"><h2>🥇 Botín de Oro</h2></div><div class="cb"><p class="subtle">Según las predicciones que subió la gente.</p>${bars(botin,Math.max(1,botin[0]?.[1]||1))}</div></div><div class="card"><div class="ch"><h2>⚽ Balón de Oro</h2></div><div class="cb"><p class="subtle">Según las predicciones que subió la gente.</p>${bars(balon,Math.max(1,balon[0]?.[1]||1))}</div></div><div class="card"><div class="ch"><h2>🎯 Acertómetro top 5</h2></div><div class="cb">${topMetric('pct','%')}</div></div></div><br><div class="card"><div class="ch"><h2>🗺️ Mapa del Mundial</h2></div><div class="cb">${worldMap()}</div></div><br><div class="card"><div class="ch"><h2>📊 Opinión colectiva</h2></div><div class="cb">${focus?`<p class="subtle">${flag(focus.local)} ${esc(focus.local)} vs ${flag(focus.visitante)} ${esc(focus.visitante)}</p>${bars(countPredictedWinner(focus),116)}`:'Sin próximo partido'}</div></div>`}
function bars(entries,max){return (entries||[]).slice(0,8).map(([name,val])=>`<div class="barrow"><div class="barhead"><span>${flag(name)} ${esc(name)}</span><b>${val}</b></div><div class="bar"><div class="fill" style="width:${pct(val,max)}%"></div></div></div>`).join('')||'<div class="empty">Sin datos</div>'}
function allTeams(){const s=new Set();MATCHES.forEach(m=>{if(m.local)s.add(m.local);if(m.visitante)s.add(m.visitante)});return [...s].sort()}
function qualifiedTeams(){const s=new Set();MATCHES.filter(m=>(m.matchId||0)>=73).forEach(m=>{if(m.local)s.add(teamKey(m.local));if(m.visitante)s.add(teamKey(m.visitante))});return s}
function worldMap(){const q=qualifiedTeams();return `<div class="map-grid">${allTeams().map(t=>`<div class="map-team ${q.has(teamKey(t))?'ok':'bad'}"><span>${flag(t)} ${esc(t)}</span><b>${q.has(teamKey(t))?'Clasificado':'Eliminado'}</b></div>`).join('')}</div>`}
function awardCard(ico,title,p,detail){return `<div class="award"><div class="ico">${ico}</div><b>${esc(title)}</b><div class="winner">${esc(p?.nombre||'-')}</div><small>${esc(detail||'')}</small></div>`}
function renderSalon(){
  const leader=RANKING[0];
  const exact=RANKING.slice().sort((a,b)=>b.exact-a.exact||b.pts-a.pts)[0];
  const pulpo=RANKING.slice().sort((a,b)=>b.pct-a.pct||b.pts-a.pts)[0];
  const grupos=RANKING.slice().sort((a,b)=>b.groupPts-a.groupPts||b.pts-a.pts)[0];
  const llaves=RANKING.slice().sort((a,b)=>b.koPts-a.koPts||b.koHit-a.koHit)[0];
  const balon=RANKING.slice().sort((a,b)=>b.hit-a.hit||b.exact-a.exact)[0];
  const awards=[
    awardCard('👑','Rey del Mundial',leader,`${leader?.pts||0} puntos`),
    awardCard('🎯','Francotirador',exact,`${exact?.exact||0} marcadores exactos`),
    awardCard('🐙','Pulpo Paul',pulpo,`${pulpo?.pct||0}% de aciertos`),
    awardCard('🌎','Visionario de grupos',grupos,`${grupos?.groupPts||0} pts por grupos · ${grupos?.groupHits||0} posiciones`),
    awardCard('🏆','Maestro de llaves',llaves,`${llaves?.koPts||0} pts · ${llaves?.koHit||0} llaves acertadas`),
    awardCard('⚽','Balón de la polla',balon,`${balon?.hit||0} resultados acertados`),
  ].join('');
  document.getElementById('salon').innerHTML=`<div class="card"><div class="ch"><h2>🏛️ Salón de la fama</h2></div><div class="cb"><div class="award-grid">${awards}</div></div></div><br><div class="grid2"><div class="card"><div class="ch"><h2>🥇 Top general</h2></div><div class="cb">${RANKING.slice(0,10).map(p=>`<div class="badge-row rank-row" onclick="openProfile('${p.id}')"><div class="pos">${medal(p.pos)}</div><div><div class="nm">${esc(p.nombre)}</div><div class="subtle">${p.exact} exactos · ${p.hit} aciertos · ${p.koPts} pts llaves</div></div><div class="pts">${p.pts}</div></div>`).join('')}</div></div><div class="card"><div class="ch"><h2>🏆 Top llaves</h2></div><div class="cb">${koLeaderboard()}</div></div></div>`
}
function needToWin(p){const leader=RANKING[0];if(!leader||p.id===leader.id)return 'Vas de primero. Lo que necesitas es mantener la ventaja en los partidos pendientes.';const diff=leader.pts-p.pts;const chances=[];PENDING.slice(0,12).forEach(m=>{const pr=p.predicciones?.[m.id], lr=leader.predicciones?.[m.id];if(!pr||!lr)return;const po=outcome(pr.golesLocal,pr.golesVisitante), lo=outcome(lr.golesLocal,lr.golesVisitante);if(po!==lo){const pick=po==='L'?m.local:po==='V'?m.visitante:'empate';chances.push(`${flag(pick)} ${pick} te ayuda frente al líder`)}});return `Estás a ${diff} puntos del líder. ${chances.length?chances.slice(0,4).join('. '):'Tus opciones dependen de acertar más marcadores exactos que el líder en los partidos pendientes.'}`}
function koProfileSummary(p){const rounds=['16avos','Octavos','Cuartos','Semis','Final'];return `<div class="ko-grid">${rounds.map(r=>{const d=p.koByRound?.[r]||{pts:0,hit:0,exact:0,total:0};return `<div class="ko-mini"><span>${r}</span><b>${d.pts} pts</b><small class="subtle">${d.hit}/${d.total} acertadas</small></div>`}).join('')}</div>`}
function koProfileDetails(p){const items=[];Object.entries(p.koByRound||{}).forEach(([r,d])=>{d.items.forEach(x=>items.push({...x,round:r}))});if(!items.length)return '<div class="empty">Aún no tiene puntos de llaves jugadas.</div>';return items.slice(0,20).map(x=>`<div class="ko-detail-row"><div><b>${esc(x.round)}</b> · ${esc(x.m.local)} ${x.m.golesLocal}-${x.m.golesVisitante} ${esc(x.m.visitante)}<div class="subtle">Predicción: ${x.pr.golesLocal}-${x.pr.golesVisitante}</div></div><div class="${x.ok?'ko-ok':'ko-bad'}">${x.ok?'✔':'✘'}</div><div class="pts">+${x.s}</div></div>`).join('')}
function openProfile(id){const p=RANKING.find(x=>x.id===id);if(!p)return;document.getElementById('profileContent').innerHTML=`<div class="prof-grid"><div>${playerCard(p)}<br><button class="btn" onclick="sharePlayer('${p.id}')">📲 Copiar para WhatsApp</button></div><div><h2 style="color:var(--gold);font-size:1.7rem">${esc(p.nombre)}</h2><p class="subtle">Puesto #${p.pos} · ${p.pts} puntos</p><div class="mini-stats"><div class="mini"><span>Aciertos</span><b>${p.hit}</b></div><div class="mini"><span>Exactos</span><b>${p.exact}</b></div><div class="mini"><span>Llaves</span><b>${p.koPts} pts</b></div></div><div class="need-box"><h4>🤖 ¿Qué necesito para ganar?</h4><p class="subtle">${esc(needToWin(p))}</p></div><h3 class="profile-section-title">🏆 Puntos por llaves</h3>${koProfileSummary(p)}<h3 class="profile-section-title">Detalle de llaves</h3>${koProfileDetails(p)}<h3 class="profile-section-title">Últimos puntos</h3>${p.last.slice(0,8).map(x=>`<div class="feed-row"><div class="feed-ico">${x.ex?'🎯':x.ok?'✅':'⚽'}</div><div><div class="feed-title">${esc(x.m.local)} ${x.m.golesLocal}-${x.m.golesVisitante} ${esc(x.m.visitante)} <span class="pill-small">+${x.s}</span></div><div class="feed-sub">Tu predicción: ${x.pr.golesLocal}-${x.pr.golesVisitante}</div></div></div>`).join('')}</div></div>`;document.getElementById('profile').classList.add('act')}
function closeProfile(){document.getElementById('profile').classList.remove('act')}
function sharePlayer(id){const p=RANKING.find(x=>x.id===id);const txt=`🏆 Polla Mundial 2026\n${p.nombre}\nPuesto #${p.pos}\n${p.pts} puntos\n🎯 ${p.exact} exactos\n⚽ ${p.hit} aciertos\n👑 Campeón elegido: ${p.honor?.campeon||'-'}`;navigator.clipboard?.writeText(txt);const t=document.getElementById('toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function renderAll(){document.getElementById('subtitle').textContent=`${PARTICIPANTES.length} participantes · ${PLAYED.length}/${MATCHES.length} partidos · ${new Date(RES?._meta?.ultima_revision_auto||Date.now()).toLocaleString('es-CO',{dateStyle:'short',timeStyle:'short'})}`;renderDashboard();renderRanking();renderPartidos();renderLlave();renderMundial();renderSalon();showTab('inicio')}
async function loadData(){try{const [p,r]=await Promise.all([fetch('predicciones.json?ts='+Date.now(),{cache:'no-store'}).then(x=>x.json()),fetch('resultados.json?ts='+Date.now(),{cache:'no-store'}).then(x=>x.json())]);PRED=p;RES=r;PARTICIPANTES=(p.participantes||[]).filter(x=>x.nombre&&x.id!=='alejandro_gonzalex');MATCHES=(r.partidos||[]).map(m=>({...m}));calculate();renderAll()}catch(e){document.getElementById('subtitle').textContent='No pude cargar los datos';document.getElementById('inicio').innerHTML=`<div class="card"><div class="cb empty">Error cargando JSON: ${esc(e.message)}</div></div>`}}
initNav();loadData();
